# Generated by Django 4.2.6 on 2023-11-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreo_del_conteo',
            name='imagen',
        ),
    ]
