# Generated by Django 4.2.6 on 2023-11-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_monitoreo_del_conteo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('contraseña', models.CharField(max_length=128)),
                ('usuario', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'login_escritorio',
            },
        ),
    ]
