# Generated by Django 4.2.6 on 2023-11-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_login_escritorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_escritorio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
