# Generated by Django 4.2.6 on 2023-11-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_login_escritorio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_escritorio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
