# Generated by Django 4.2.6 on 2023-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_login_escritorio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_escritorio',
            name='id_usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login_escritorio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
