# Generated by Django 4.2.6 on 2023-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_login_escritorio_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_escritorio',
            name='apellidos',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
